[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#00ff00"
text = "CellBackground"

[colors.primary]
background = "#151515"
bright_foreground = "#fafafa"
foreground = "#e0e0e0"

[font]
size = 12.0

[font.normal]
family = "xos4 Terminus"
style = "Regular"
